"""Initial migration

Revision ID: 774001744060
Revises: 8b8a6444edf6
Create Date: 2025-11-18 22:34:30.106697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "774001744060"
down_revision: Union[str, Sequence[str], None] = "8b8a6444edf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "book", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_book_library_id"), "book", ["library_id"], unique=False)
    op.create_index(op.f("ix_book_user_id"), "book", ["user_id"], unique=False)
    op.add_column(
        "library", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("library", "updated_at")
    op.drop_index(op.f("ix_book_user_id"), table_name="book")
    op.drop_index(op.f("ix_book_library_id"), table_name="book")
    op.drop_column("book", "updated_at")
    op.drop_column("book", "created_at")
    # ### end Alembic commands ###
