"""clean many-to-many user-library

Revision ID: 8b8a6444edf6
Revises: de7e8ee4ea1e
Create Date: 2025-10-18 18:49:19.475539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b8a6444edf6"
down_revision: Union[str, Sequence[str], None] = "de7e8ee4ea1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
