"""Add user_book_status table

Revision ID: ba015b737e3f
Revises: 347d6de5eeb1
Create Date: 2025-11-22 21:10:53.778189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba015b737e3f'
down_revision: Union[str, Sequence[str], None] = '347d6de5eeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'read_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('read_status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
