"""Initial migration

Revision ID: c6d5bf17aca3
Revises: 801b6a6d8a4e
Create Date: 2025-11-26 16:37:12.665140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d5bf17aca3'
down_revision: Union[str, Sequence[str], None] = '801b6a6d8a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
