"""Initial migration

Revision ID: d93c98016418
Revises: c6d5bf17aca3
Create Date: 2025-11-27 20:37:51.363480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d93c98016418"
down_revision: Union[str, Sequence[str], None] = "c6d5bf17aca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_slug"), "user", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_slug"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
